language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install tox-travis
  - pip install coveralls

env:
  global:
    - TRAVIS="True"

script:
  - pandoc --from=markdown --to=rst --output=README.rst README.md
  - tox

after_success:
  coveralls

notifications:
  email:
    recipients:
      - marc@helium.com
    on_failure: change
    on_success: never

deploy:
  - provider: pypi
    skip_cleanup: true
    user: madninja
    on:
      tags: true
      distributions: "sdist bdist_wheel"
      repo: helium/helium-commander
    password:
      secure: hu+tqO6meVYyhcfnAs3eSh564dfo4IveaSuEVNVSS6VSJZUbyzorllyw/iUW+KvRx4D2Ek9ey2IXfT0gvvY/oDbBf2dwoBJgxbkWHDgOJLf0T206yqu+JHr4NSVZxbPFs33kunXPDFgAEcpPvqBuuGi6z2Hpl5jLYp83knAQKyEsOl3lHZeFBeMbq1cQk2oQQtuVDaapTNTZEiIMh7+p9AzYYMw0Q04QvxwIyq2C3yvggTYu8KHyzrNaVZ6IcfMy1OmjVB4+a7v/FlZRZLElqjD5woUuyeZJjy+Cc/fOBsVONrpz3wXyXDnXsC+aWBB6eLdUaNZzvtcebePmDFblmjE+SvJ8xOQVBR2OsSRT12zdPhXqhJKuyBaB2e388vyIC878qsNChqUbBSZpv8+QtuK7sRVwXFOY5VUl4QnxNdzOKBz+FLTDDTqWGvpo3tJgH6JLFaKBdDYpM7oPCI32j0PyaejqAWv1mxbx5QkY7lEJRQ/RsE2yp7DdKWM8OX5TlwpKNYiuzSY1eTLByHseikxIPd3EiL10pp5wtx7heM4wIjynf1wsU5mAmBQbcEsLi8/LxGEZufg9pY0z0oJPZTXyTVJ9aYvmWKJOekq7pecXZ2SQWJpUVasW2GxojpafoW72h9vrUHG6GDVA1d51qNyWb3WrjTst812f7raIiyw=
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      repo: helium/helium-commander
    api_key:
      secure: ljl9/OQIqpTbwt31tzcZ1SN56aNCjTLEpmwNwI0DY2qHdHCHzvwN0RSB4boWP8z0/w+CR5D4gcskrywD/7MaWfACLUnrepczPjbk9sGugI72mFFzKwNMeKDXooM4NrVIwHl+SAfVkwo8YKA3YY2RUiSA47oIZEjqceS4nzF25E2vnMGQi6T6CFqV/POKYgBdiu3gWAe/g8LYg5O/uXp+DO5ybyFDO6YYuKcfP4/ngKk17BDmHC2xHYMhsP10r9dCN4alDHp0IKNapre5dzwXxto7B6uXywT+YBNGxnXrZDdcQSs8N8D0sU1l8x5dB74gTeHZgM82nDA5Z6LzYYhkwQQ5+cIDJiCedQ9ObaeHCHfCYKNgOo0AFSPOqgLDj9TiZABRGuZCTDVd4fb3dw0Ifk8BQm63QpVKNRDJhwSnKffNvB61bxKUHSxd2MT2M6GF7dBWvWhG8d54vTQXpsP61CfQdpryyQErbj6pfRaRJ2K6r7wYBnNEetLM5bYH5n4NAJWzXtSCojC7W7Y2F85fkf0cNh/fhDGt8f3eMDaTa2KCo8tGrxaTyoLL3UtTWrL4tObuTOa5bAMiMLasRFhqrZe+FfepFiXd4vJ2sNrnBs1n5FTkEigBo4vYyOcRwaF85fivgTnpQXo9zc54ETqUYY0eWIwCTyxu+Vn32yPWymE=
